apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      completions: 5 # Espera que se terminen 5 pods para finalizar
      parallelism: 2 # Pods que se van a crear a la vez
      #template:     con esto hacemos lo mismo que select control, 
        #nodoSelector:
          #Kubernete.io/os: linux      
      containers: # Plantilla del pod que crea el Job
      - name: pi
        image: perl:5.34.0
        command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never 