apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ejercicio
spec:
  storageClassName: ejercicio
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv001 # Aqui no estamos usando aun una clase de almacenamiento, sino el aprovisionador hostPad