apiVersion: v1
kind: Pod
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  containers:
  - image: lemoncodersbc/go-hello-world
    name: helloworld
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
