apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: helloworld-rs
  labels:
    app: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: lemoncodersbc/go-hello-world
        name: helloworld
      dnsPolicy: ClusterFirst
      restartPolicy: Always

