apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app
spec:
  ingressClassName: nginx
  rules:
    - host: testjose.xyz
      http:
        paths:        
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-front-svc
                port:
                  number: 80    
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: todo-api-svc
                port:
                  number: 3000  