apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: showinfo
  name: showinfo
spec:
  containers:
  - image: lemoncodersbc/showinfo:v1
    name: showinfo
    env:
    - name: TEST_ENV
      value: "A Simple Test Value"      
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
