apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: wpall
  name: wpall
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: my-secret-pw
    - name: MYSQL_DATABASE
      value: lcwp
    - name: MYSQL_USER
      value: eiximenis
    - name: MYSQL_PASSWORD
      value: Pa+a+a1!
    image: mysql:5
    name: mysql
    ports:
    - containerPort: 3306
    resources: {}
  - env:
    - name: WORDPRESS_DB_HOST
      value: "127.0.0.1"
    - name: WORDPRESS_DB_NAME
      value: lcwp
    - name: WORDPRESS_DB_USER
      value: eiximenis
    - name: WORDPRESS_DB_PASSWORD
      value: Pa+a+a1!
    image: wordpress:php7.2
    name: wp
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
