apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app01
  name: todo-app-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: todo-app01
  type: LoadBalancer 